language: python
python:
  - "2.7"
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-linux64.tar.gz
  - tar zxf geckodriver-v0.14.0-linux64.tar.gz
  - mv geckodriver /usr/local/bin
  - sudo apt-get -qq update
  - sudo apt-get install -y -qq slapd ldap-utils
  - pip install --upgrade pip
  - pip install -r requirements-mysql.txt -r requirements-dev.txt
  - pip install -r requirements-pgsql.txt
before_script:
  - pushd docs/ldap; DEBUG=true ./startldap.sh; popd
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./runtests.sh --lint-only
  - mysql -e 'create database IF NOT EXISTS rattic;'
  - psql -c 'create database rattic;' -U postgres
script:
  - echo -e '[ratticweb]\nsecretkey = blah!' > conf/local.cfg
  - ./runtests.sh --tests-only

  - cp docs/travis/ldap.cfg conf/local.cfg
  - ./runtests.sh --tests-only

  - cp docs/travis/mysql.cfg conf/local.cfg
  - python manage.py syncdb --noinput
  - python manage.py migrate
  - ./runtests.sh --tests-only

  - cp docs/travis/pgsql.cfg conf/local.cfg
  - python manage.py syncdb --noinput
  - python manage.py migrate
  - ./runtests.sh --tests-only
