language: python
python:
  - "2.7"
addons:
  firefox: "52.0"
cache:
  directories:
    - $HOME/.pip-cache/
install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.14.0/geckodriver-v0.14.0-linux64.tar.gz
  - tar zxf geckodriver-v0.14.0-linux64.tar.gz
  - sudo mv geckodriver /usr/local/bin
  - sudo apt-get -qq update
  - sudo apt-get install -y -qq slapd ldap-utils
  - sudo apt-get install -y -qq libzbar-dev python-dev
  - pip install --upgrade pip
  - pip install -r requirements-mysql.txt -r requirements-dev.txt
#  - pip install -r requirements-pgsql.txt
before_script:
  - pushd docs/ldap; DEBUG=true ./startldap.sh; popd
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./runtests.sh --lint-only
#  - mysql -u root -e 'create database IF NOT EXISTS rattic character set utf8 collate utf8_unicode_ci;'
#  - psql -c "create database rattic WITH ENCODING 'UTF8' TEMPLATE=template0" -U postgres
script:
  - cp docs/travis/local.cfg conf/local.cfg
  - python manage.py collectstatic --noinput
  - python manage.py makemigrations
  - python manage.py migrate
  - ./runtests.sh --tests-only

  - cp docs/travis/ldap.cfg conf/local.cfg
  - ./runtests.sh --tests-only

# # RatticDB cannot run on MySQL
#   - cp docs/travis/mysql.cfg conf/local.cfg
#   - python manage.py makemigrations
#   - python manage.py migrate
#   - ./runtests.sh --tests-only
# 
# # RatticDB cannot run on PostgreSQL
#   - cp docs/travis/pgsql.cfg conf/local.cfg
#   - python manage.py makemigrations
#   - python manage.py migrate
#   - ./runtests.sh --tests-only
